### ISSUE TITLE
build not up to date?

### ISSUE THREAD

**Issue by tirrorex** [zman0900/aur-libvirt-git#1]
Hi mate, i thought this was using libvirt sources?
I need a version of libvirt with a commit 3weeks old : http://libvirt.org/git/?p=libvirt.git;a=commit;h=7068b56c8526667750d8cb91116e9b40382422f3 
But apparently yours don't have it, any idea on how to modify the pkgbuild to fix this?
Thanks

**Comment by zman0900** [comment]
The source is the master branch of that git repo, so it should have that commit unless it has been reverted since then.  Each time you build with makepkg, it should update the git source to HEAD.

**Comment by tirrorex** [comment]
Seems that some dependencies are missing.
ebtables and dmidecode.
But even after downloading the packages libvirtd fails to start :  

$ systemctl start libvirtd.service
Job for libvirtd.service failed because a timeout was exceeded. See "systemctl status libvirtd.service" and "journalctl -xe" for details.

# root @ arch64 in /home/zipeldiablo [14:19:32] C:1

$ systemctl status libvirtd.service
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: disabled)
   Active: activating (start) since Sat 2016-04-16 14:19:32 CEST; 19s ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 4428 (libvirtd)
    Tasks: 18 (limit: 512)
   CGroup: /system.slice/libvirtd.service
           ├─4176 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
           ├─4177 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
           └─4428 /usr/bin/libvirtd

Apr 16 14:19:32 arch64 systemd[1]: Starting Virtualization daemon...
Apr 16 14:19:32 arch64 dnsmasq[4176]: read /etc/hosts - 2 addresses
Apr 16 14:19:32 arch64 dnsmasq[4176]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Apr 16 14:19:32 arch64 dnsmasq-dhcp[4176]: read /var/lib/libvirt/dnsmasq/default.hostsfile

So i can not test this :/ 
Will update after i find a fix, the commit i'm looking for is on master apparently

**Comment by tirrorex** [comment]
This is a known libvirt issue, running this to solve it : 

# cp /usr/lib/systemd/system/libvirtd.service /etc/systemd/system/libvirtd.service

# sed -i s/notify/simple/ /etc/systemd/system/libvirtd.service

# systemctl daemon-reload

# systemctl reenable libvirtd     # If you enabled it before
